language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./MicroBot.py
  - python -m compileall ./cogs
  - python ./MicroBot.py --no-prompt --no-cogs --dry-run
cache: pip
notifications:
email: false
